### ISSUE TITLE
Search API response with duplicate 'user' key

### ISSUE THREAD

**Issue by ricky300300** [unsplash/unsplash-source-js#20] opened 2018-03-27 11:00 UTC
search api is returning duplicate 'user' key in JSON response.

Below is one response
`{"total":7991,"total_pages":7991,"results":[{"id":"Pw5uvsFcGF4","created_at":"2018-01-21T21:45:51-05:00","updated_at":"2018-01-23T07:15:50-05:00","width":5760,"height":3840,"color":"#070A0B","description":null,"categories":[],"user":{"id":"AJaSdqYUTig","updated_at":"2018-03-26T05:07:39-04:00","username":"jtylernix","name":"Tyler Nix","first_name":"Tyler","last_name":"Nix","twitter_username":null,"portfolio_url":"http://tylernixcreative.com","bio":"Lifestyle and branding photographer based in Los Angeles, California.","location":"Los Angeles, CA","links":{"self":"https://api.unsplash.com/users/jtylernix","html":"https://unsplash.com/@jtylernix","photos":"https://api.unsplash.com/users/jtylernix/photos","likes":"https://api.unsplash.com/users/jtylernix/likes","portfolio":"https://api.unsplash.com/users/jtylernix/portfolio","following":"https://api.unsplash.com/users/jtylernix/following","followers":"https://api.unsplash.com/users/jtylernix/followers"},"profile_image":{"small":"https://images.unsplash.com/profile-1517513712094-26168c2381bc?ixlib=rb-0.3.5&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=32&w=32&s=bd7dcbc855cf74773ef1a50e5bb04c08","medium":"https://images.unsplash.com/profile-1517513712094-26168c2381bc?ixlib=rb-0.3.5&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=64&w=64&s=1d9c6e53cc6c5cbf3420a938301256a2","large":"https://images.unsplash.com/profile-1517513712094-26168c2381bc?ixlib=rb-0.3.5&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=128&w=128&s=2dab2cacea35e449951d29a9f5f3f42b"},"total_collections":0,"instagram_username":"jtylernix","total_likes":802,"total_photos":315},"urls":{"raw":"https://images.unsplash.com/photo-1516589091380-5d8e87df6999?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjcyMDF9&s=634deb70e819d4a15a94813664223bc6","full":"https://images.unsplash.com/photo-1516589091380-5d8e87df6999?ixlib=rb-0.3.5&q=85&fm=jpg&crop=entropy&cs=srgb&ixid=eyJhcHBfaWQiOjcyMDF9&s=032a7572d3165c9935b58e39d94c3b4f","regular":"https://images.unsplash.com/photo-1516589091380-5d8e87df6999?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjcyMDF9&s=971f4f2fc02403d8a3dd76384474d3d8","small":"https://images.unsplash.com/photo-1516589091380-5d8e87df6999?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max&ixid=eyJhcHBfaWQiOjcyMDF9&s=aec96bf5576b139445351f836e7a1b6f","thumb":"https://images.unsplash.com/photo-1516589091380-5d8e87df6999?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=200&fit=max&ixid=eyJhcHBfaWQiOjcyMDF9&s=9a96cb92d06572a9d874b1f5c49d0f40"},"links":{"self":"https://api.unsplash.com/photos/Pw5uvsFcGF4","html":"https://unsplash.com/photos/Pw5uvsFcGF4","download":"https://unsplash.com/photos/Pw5uvsFcGF4/download","download_location":"https://api.unsplash.com/photos/Pw5uvsFcGF4/download"},"liked_by_user":false,"sponsored":false,"likes":157,"user":{"id":"AJaSdqYUTig","updated_at":"2018-03-26T05:07:39-04:00","username":"jtylernix","name":"Tyler Nix","first_name":"Tyler","last_name":"Nix","twitter_username":null,"portfolio_url":"http://tylernixcreative.com","bio":"Lifestyle and branding photographer based in Los Angeles, California.","location":"Los Angeles, CA","links":{"self":"https://api.unsplash.com/users/jtylernix","html":"https://unsplash.com/@jtylernix","photos":"https://api.unsplash.com/users/jtylernix/photos","likes":"https://api.unsplash.com/users/jtylernix/likes","portfolio":"https://api.unsplash.com/users/jtylernix/portfolio","following":"https://api.unsplash.com/users/jtylernix/following","followers":"https://api.unsplash.com/users/jtylernix/followers"},"profile_image":{"small":"https://images.unsplash.com/profile-1517513712094-26168c2381bc?ixlib=rb-0.3.5&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=32&w=32&s=bd7dcbc855cf74773ef1a50e5bb04c08","medium":"https://images.unsplash.com/profile-1517513712094-26168c2381bc?ixlib=rb-0.3.5&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=64&w=64&s=1d9c6e53cc6c5cbf3420a938301256a2","large":"https://images.unsplash.com/profile-1517513712094-26168c2381bc?ixlib=rb-0.3.5&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=128&w=128&s=2dab2cacea35e449951d29a9f5f3f42b"},"total_collections":0,"instagram_username":"jtylernix","total_likes":802,"total_photos":315},"current_user_collections":[],"photo_tags":[{"title":"love"},{"title":"hand gestures"},{"title":"friendship"},{"title":"friends"},{"title":"l"}]}]}`

**Comment by aaronklaassen** [comment] 2018-03-27 18:35
Hey @ricky300300. I'm going to close this because it's not an issue with this repo and we're not seeing this behaviour API-side. If you're still seeing this bug, it'd be great if you could send a reproduction/test details to api@unsplash.com. Thanks.

**Closed as completed by aaronklaassen** 2018-03-27 18:35 UTC
